### ISSUE TITLE
Deploy na Vercel

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademy/frontend-web-intermediario-nextjs-typescript#5]
**Descrição:** Fazer o deploy da aplicação na Vercel para tornar a aplicação acessível online.
**Tarefas:** Configurar Vercel, ajustar configurações de ambiente do Next.js e TypeScript se necessário.
**Objetivo:** Facilitar o acesso ao projeto e permitir que futuros ajustes sejam visualizados online.

**Comment by profissao-dev-frontend-javascript** [comment]
URL: https://frontend-web-intermediario-nextjs-typescript.vercel.app/
